sudo: required
services:
    - docker

before_install:
    - docker build -t pradyumnadocker/docker-react -f Dockerfile.dev .

script:
    - docker run pradyumnadocker/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Dockerreact"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-2-854163894608" 
    bucket_path: "Dockerreact"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"